variable "aws_region" {
  type        = string
  description = "AWS region for the Lambda function."
  default     = "us-east-1"
}

variable "project_name" {
  type        = string
  description = "Name for AWS resources and Lambda log group."
  default     = "telegram-photo-geolocator-bot"
}

variable "lambda_zip_path" {
  type        = string
  description = "Path to Lambda zip generated by scripts/build-lambda.sh."
  default     = "../build/lambda.zip"
}

variable "telegram_bot_token" {
  type        = string
  description = "Telegram bot token from BotFather. Stored in Terraform state."
  sensitive   = true
}

variable "telegram_webhook_secret" {
  type        = string
  description = "Secret sent by Telegram in X-Telegram-Bot-Api-Secret-Token."
  sensitive   = true
}

variable "github_url" {
  type        = string
  description = "Project URL used in help text and API User-Agent strings."
  default     = "https://github.com/vitaly-zdanevich/bot_telegram_geolocation_from_photo"
}

variable "lambda_memory_size" {
  type        = number
  description = "Lambda memory in MB. 3008 MB is the requested 3 GB ARM Lambda size."
  default     = 3008
}

variable "lambda_timeout_seconds" {
  type        = number
  description = "Lambda timeout for Telegram webhook processing."
  default     = 900
}

variable "max_file_mb" {
  type        = number
  description = "Maximum Telegram image file size to download."
  default     = 20
}

variable "enable_reverse_geocoding" {
  type        = bool
  description = "Enable OpenStreetMap Nominatim reverse geocoding for place names."
  default     = true
}

variable "nominatim_base_url" {
  type        = string
  description = "Nominatim reverse geocoding endpoint."
  default     = "https://nominatim.openstreetmap.org/reverse"
}

variable "nominatim_email" {
  type        = string
  description = "Optional email parameter for Nominatim operator contact."
  default     = ""
}

variable "nominatim_accept_language" {
  type        = string
  description = "Optional Accept-Language value for Nominatim place names."
  default     = ""
}

variable "enable_wikimedia_lookup" {
  type        = bool
  description = "Enable nearby Wikidata and Wikipedia lookup."
  default     = true
}

variable "wikipedia_language" {
  type        = string
  description = "Legacy comma-separated Wikipedia language fallback list used when wikipedia_languages is empty."
  default     = "en,ru,be"
}

variable "wikipedia_languages" {
  type        = list(string)
  description = "Wikipedia language editions used for nearby article lookup, in fallback order."
  default     = []
}

variable "wikipedia_api_url" {
  type        = string
  description = "Optional override for one MediaWiki Action API URL. When set, only the first configured Wikipedia language is queried directly."
  default     = ""
}

variable "wikidata_sparql_url" {
  type        = string
  description = "Wikidata Query Service SPARQL endpoint."
  default     = "https://query.wikidata.org/sparql"
}

variable "wikimedia_radius_meters" {
  type        = number
  description = "Nearby search radius for Wikidata and Wikipedia results."
  default     = 10000
}

variable "wikimedia_limit" {
  type        = number
  description = "Maximum nearby Wikidata and Wikipedia results each."
  default     = 5
}

variable "reserved_concurrent_executions" {
  type        = number
  description = "Reserved Lambda concurrency. Use -1 for no function-level reservation."
  default     = -1
}
